version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    
  
  dbadmin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=postgres
